export const MOCK_JOBS = [
  {
    jobId: 'job_001',
    title: 'Senior Frontend Developer',
    company: 'TCS',
    location: 'Mumbai',
    category: 'IT & Software',
    workType: 'Hybrid',
    experience: '3-5 years',
    salary: '18-25 LPA',
    description: 'We are looking for an experienced React developer to join our product team. You will build scalable web applications and work closely with design and backend teams.',
    skills: ['React', 'TypeScript', 'AWS', 'Node.js'],
    postedDaysAgo: 1,
    applicantCount: 47,
  },
  {
    jobId: 'job_002',
    title: 'Risk Analyst',
    company: 'HDFC Bank',
    location: 'Pune',
    category: 'Banking & Finance',
    workType: 'On-site',
    experience: '2-4 years',
    salary: '12-18 LPA',
    description: 'Analyze credit risk, market risk and operational risk. Prepare risk reports and work with compliance teams to ensure regulatory requirements are met.',
    skills: ['Risk Management', 'Excel', 'SQL', 'Compliance'],
    postedDaysAgo: 2,
    applicantCount: 23,
  },
  {
    jobId: 'job_003',
    title: 'Staff Nurse – ICU',
    company: 'Apollo Hospitals',
    location: 'Chennai',
    category: 'Healthcare & Medical',
    workType: 'On-site',
    experience: '1-3 years',
    salary: '4-7 LPA',
    description: 'Provide critical care nursing in ICU settings. Monitor patients, administer medications and coordinate with doctors for treatment plans.',
    skills: ['ICU Care', 'BLS', 'Patient Monitoring', 'Critical Care'],
    postedDaysAgo: 3,
    applicantCount: 18,
  },
  {
    jobId: 'job_004',
    title: 'Recruitment Consultant',
    company: 'TeamLease',
    location: 'Bangalore',
    category: 'HR & Recruitment',
    workType: 'Hybrid',
    experience: '1-3 years',
    salary: '6-10 LPA',
    description: 'End-to-end recruitment for multiple clients across industries. Source candidates, conduct screenings and manage client relationships.',
    skills: ['Sourcing', 'Client Management', 'LinkedIn', 'ATS'],
    postedDaysAgo: 4,
    applicantCount: 31,
  },
  {
    jobId: 'job_005',
    title: 'Backend Engineer',
    company: 'Infosys',
    location: 'Hyderabad',
    category: 'IT & Software',
    workType: 'Remote',
    experience: '2-4 years',
    salary: '14-20 LPA',
    description: 'Build and maintain microservices using Node.js and AWS Lambda. Work on serverless architecture and DynamoDB data modeling.',
    skills: ['Node.js', 'AWS Lambda', 'DynamoDB', 'REST APIs'],
    postedDaysAgo: 5,
    applicantCount: 62,
  },
  {
    jobId: 'job_006',
    title: 'Compliance Officer',
    company: 'Axis Bank',
    location: 'Mumbai',
    category: 'Banking & Finance',
    workType: 'On-site',
    experience: '3-6 years',
    salary: '15-22 LPA',
    description: 'Ensure bank operations comply with RBI regulations and internal policies. Conduct audits and prepare compliance reports.',
    skills: ['RBI Guidelines', 'Audit', 'Risk Assessment', 'Reporting'],
    postedDaysAgo: 2,
    applicantCount: 15,
  },
  {
    jobId: 'job_007',
    title: 'Full Stack Developer',
    company: 'Razorpay',
    location: 'Bangalore',
    category: 'IT & Software',
    workType: 'Hybrid',
    experience: '2-5 years',
    salary: '20-35 LPA',
    description: 'Work on Razorpay payment products. Build features end to end from React frontend to Node.js backend with high scale requirements.',
    skills: ['React', 'Node.js', 'PostgreSQL', 'Redis'],
    postedDaysAgo: 1,
    applicantCount: 89,
  },
  {
    jobId: 'job_008',
    title: 'HR Business Partner',
    company: 'Deloitte',
    location: 'Gurgaon',
    category: 'HR & Recruitment',
    workType: 'Hybrid',
    experience: '4-7 years',
    salary: '16-24 LPA',
    description: 'Partner with business leaders on talent strategy, performance management and organizational development initiatives.',
    skills: ['HR Strategy', 'Talent Management', 'OD', 'Stakeholder Management'],
    postedDaysAgo: 6,
    applicantCount: 28,
  },
];

export const MOCK_RECRUITER_JOBS = [
  {
    jobId: 'rjob_001',
    title: 'Senior Frontend Developer',
    company: 'TCS',
    category: 'IT & Software',
    workType: 'Hybrid',
    experience: '3-5 years',
    salary: '18-25 LPA',
    location: 'Mumbai',
    description: 'Looking for experienced React developer.',
    skills: ['React', 'TypeScript', 'AWS'],
    postedDaysAgo: 2,
    applicantCount: 4,
    status: 'Active',
  },
  {
    jobId: 'rjob_002',
    title: 'Risk Analyst',
    company: 'HDFC Bank',
    category: 'Banking & Finance',
    workType: 'On-site',
    experience: '2-4 years',
    salary: '12-18 LPA',
    location: 'Pune',
    description: 'Analyze credit and market risk.',
    skills: ['Risk Management', 'SQL', 'Excel'],
    postedDaysAgo: 5,
    applicantCount: 3,
    status: 'Active',
  },
  {
    jobId: 'rjob_003',
    title: 'HR Business Partner',
    company: 'Deloitte',
    category: 'HR & Recruitment',
    workType: 'Hybrid',
    experience: '4-7 years',
    salary: '16-24 LPA',
    location: 'Bangalore',
    description: 'Partner with business leaders on talent strategy.',
    skills: ['HR Strategy', 'Talent Management', 'OD'],
    postedDaysAgo: 8,
    applicantCount: 5,
    status: 'Active',
  },
];

export const MOCK_APPLICANTS_BY_JOB = {
  'rjob_001': [
    {
      candidateId: 'c_001',
      name: 'Arjun Mehta',
      email: 'arjun.mehta@gmail.com',
      phone: '+91 98765 43210',
      experience: '5 years',
      appliedDate: '2 days ago',
      score: 92,
      strengths: ['React', 'TypeScript', 'AWS', 'System Design'],
      gaps: ['GraphQL'],
      summary: 'Arjun is an exceptional frontend engineer with deep React expertise and solid AWS experience. His system design skills are above average for his experience level. The only notable gap is GraphQL which is a minor requirement for this role. Highly recommended for shortlisting.',
    },
    {
      candidateId: 'c_002',
      name: 'Sneha Kulkarni',
      email: 'sneha.k@outlook.com',
      phone: '+91 87654 32109',
      experience: '3 years',
      appliedDate: '3 days ago',
      score: 78,
      strengths: ['Node.js', 'CSS', 'Redux', 'React'],
      gaps: ['AWS', 'TypeScript'],
      summary: 'Sneha has strong frontend fundamentals and good React experience. She lacks AWS exposure which is a key requirement. TypeScript is missing from her profile but she has JavaScript expertise. Worth considering for a junior version of this role.',
    },
    {
      candidateId: 'c_003',
      name: 'Rohan Sharma',
      email: 'rohan.sharma@gmail.com',
      phone: '+91 76543 21098',
      experience: '2 years',
      appliedDate: '4 days ago',
      score: 61,
      strengths: ['Redux', 'React basics'],
      gaps: ['AWS', 'TypeScript', 'Testing', 'System Design'],
      summary: 'Rohan is an early-career developer with basic React skills. He has significant gaps in the key technical requirements — AWS, TypeScript, and testing. Not recommended for this senior role but could be considered for a junior opening.',
    },
    {
      candidateId: 'c_004',
      name: 'Fatima Shaikh',
      email: 'fatima.s@yahoo.com',
      phone: '+91 65432 10987',
      experience: '1 year',
      appliedDate: '5 days ago',
      score: 34,
      strengths: ['HTML', 'CSS'],
      gaps: ['React', 'JavaScript', 'AWS', 'TypeScript'],
      summary: 'Fatima is very early in her career with limited JavaScript experience. She does not yet meet the minimum requirements for this senior frontend role. Not recommended at this stage.',
    },
  ],
  'rjob_002': [
    {
      candidateId: 'c_005',
      name: 'Vikram Nair',
      email: 'vikram.nair@gmail.com',
      phone: '+91 94321 09876',
      experience: '4 years',
      appliedDate: '1 day ago',
      score: 88,
      strengths: ['Risk Management', 'SQL', 'Excel', 'Compliance'],
      gaps: ['Python'],
      summary: 'Vikram has excellent risk management credentials with strong SQL and compliance skills. His Excel modeling experience is particularly relevant. Minor gap in Python which is not critical for this role. Strong candidate.',
    },
    {
      candidateId: 'c_006',
      name: 'Priya Desai',
      email: 'priya.desai@gmail.com',
      phone: '+91 83210 98765',
      experience: '3 years',
      appliedDate: '3 days ago',
      score: 72,
      strengths: ['Excel', 'Financial Modeling', 'Reporting'],
      gaps: ['SQL', 'Risk Frameworks'],
      summary: 'Priya has solid financial modeling experience but lacks formal risk framework knowledge. SQL skills are basic. She would benefit from additional risk management training but has a good foundation.',
    },
    {
      candidateId: 'c_007',
      name: 'Karan Mehta',
      email: 'karan.m@outlook.com',
      phone: '+91 72109 87654',
      experience: '2 years',
      appliedDate: '4 days ago',
      score: 45,
      strengths: ['Excel'],
      gaps: ['SQL', 'Risk Management', 'Compliance', 'Reporting'],
      summary: 'Karan has limited experience in risk analysis. His profile does not match the key requirements for this role. Not recommended.',
    },
  ],
  'rjob_003': [
    {
      candidateId: 'c_008',
      name: 'Meera Iyer',
      email: 'meera.iyer@gmail.com',
      phone: '+91 91098 76543',
      experience: '6 years',
      appliedDate: '1 day ago',
      score: 91,
      strengths: ['HR Strategy', 'Talent Management', 'OD', 'Stakeholder Management'],
      gaps: ['International HR'],
      summary: 'Meera is an outstanding HR professional with comprehensive HRBP experience. Her talent management and OD skills are exactly what this role requires. International HR exposure is the only gap. Top candidate.',
    },
    {
      candidateId: 'c_009',
      name: 'Aditya Rao',
      email: 'aditya.rao@gmail.com',
      phone: '+91 80987 65432',
      experience: '5 years',
      appliedDate: '2 days ago',
      score: 81,
      strengths: ['Talent Management', 'Recruitment', 'HR Operations'],
      gaps: ['OD', 'Strategic HR'],
      summary: 'Aditya has strong talent management credentials. He lacks strategic HR and OD experience which are important for a HRBP role. Good candidate with growth potential.',
    },
    {
      candidateId: 'c_010',
      name: 'Nisha Patel',
      email: 'nisha.patel@outlook.com',
      phone: '+91 70876 54321',
      experience: '4 years',
      appliedDate: '3 days ago',
      score: 67,
      strengths: ['HR Operations', 'Payroll'],
      gaps: ['Strategy', 'OD', 'Stakeholder Management'],
      summary: 'Nisha has solid HR operations experience but is primarily transactional. The HRBP role requires more strategic capability than her profile demonstrates.',
    },
    {
      candidateId: 'c_011',
      name: 'Rahul Gupta',
      email: 'rahul.g@gmail.com',
      phone: '+91 60765 43210',
      experience: '3 years',
      appliedDate: '5 days ago',
      score: 52,
      strengths: ['Recruitment'],
      gaps: ['HR Strategy', 'OD', 'Talent Management', 'Stakeholder Management'],
      summary: 'Rahul has basic recruitment experience but lacks the HRBP competencies required. Not suitable for this senior role.',
    },
    {
      candidateId: 'c_012',
      name: 'Divya Singh',
      email: 'divya.s@yahoo.com',
      phone: '+91 50654 32109',
      experience: '2 years',
      appliedDate: '6 days ago',
      score: 38,
      strengths: ['HR Basics'],
      gaps: ['Strategy', 'OD', 'Talent Management', 'HRBP Experience'],
      summary: 'Divya is too early in her HR career for this senior HRBP position. Not recommended.',
    },
  ],
};
